### ISSUE TITLE
ERROR: Failed building wheel for pendulum

### ISSUE THREAD

**Issue by tania010** [danielhoherd/plexdl#48]
I've tried installing pendulum every which way, there is always one error or another.

Collecting six>=1.5 (from python-dateutil<3.0,>=2.6->pendulum<3.0.0,>=2.1.2->plexdl==0.4.2)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using cached humanize-4.8.0-py3-none-any.whl (117 kB)
Using cached importlib_metadata-6.8.0-py3-none-any.whl (22 kB)
Using cached PlexAPI-4.15.4-py3-none-any.whl (158 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached zipp-3.17.0-py3-none-any.whl (7.4 kB)
Building wheels for collected packages: plexdl, pendulum
  Building wheel for plexdl (pyproject.toml): started
  Building wheel for plexdl (pyproject.toml): finished with status 'done'
  Created wheel for plexdl: filename=plexdl-0.4.2-py3-none-any.whl size=5864 sha256=fd235b1b1dd7c770540281a1ac875d006e44fca7a9e1a4957d84bde16a621e38
  Stored in directory: C:\Users\aaaaaa\AppData\Local\Temp\pip-ephem-wheel-cache-g9wvewgm\wheels\ed\e4\a1\f96997bf9cc7698937cad0892abce9a3e8dd9a23e8a2a5743c
  Building wheel for pendulum (pyproject.toml): started
  Building wheel for pendulum (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  Building wheel for pendulum (pyproject.toml) did not run successfully.
  exit code: 1

  [27 lines of output]
  Traceback (most recent call last):
    File "C:\Users\aaaaaa\AppData\Local\Temp\pip-install-avfoevxa\pendulum_2e47f1a564f2458d887281c92150dc7c\build.py", line 5, in <module>
      from distutils.command.build_ext import build_ext
  ModuleNotFoundError: No module named 'distutils'
  Traceback (most recent call last):
    File "C:\Users\aaaaaa\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\aaaaaa\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\aaaaaa\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\aaaaaa\AppData\Local\Temp\pip-build-env-_wjvsrf8\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 57, in build_wheel
      return WheelBuilder.make_in(
             ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\aaaaaa\AppData\Local\Temp\pip-build-env-_wjvsrf8\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 87, in make_in
      wb.build(target_dir=directory)
    File "C:\Users\aaaaaa\AppData\Local\Temp\pip-build-env-_wjvsrf8\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 122, in build
      self._build(zip_file)
    File "C:\Users\aaaaaa\AppData\Local\Temp\pip-build-env-_wjvsrf8\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 171, in _build
      self._run_build_script(self._package.build_script)
    File "C:\Users\aaaaaa\AppData\Local\Temp\pip-build-env-_wjvsrf8\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 231, in _run_build_script
      subprocess.check_call([self.executable.as_posix(), build_script])
    File "C:\Users\aaaaaa\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 413, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['C:/Users/obed/AppData/Local/Programs/Python/Python312/python.exe', 'build.py']' returned non-zero exit status 1.
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pendulum
Successfully built plexdl
Failed to build pendulum
ERROR: Could not build wheels for pendulum, which is required to install pyproject.toml-based projects

**Comment by danielhoherd** [comment]
@tania010 this repo is not the pendulum project. Pendulum is at https://github.com/sdispater/pendulum
